### PR TITLE
#245: cast fix using `JVMBridgeBase.Wraps`

### LINKED ISSUE #245: The object cast does not work right without `JVMBridgeBase.Wraps`
The cast of https://github.com/masesgroup/KNet/blob/82d8b87a7f5b6dd3451bf77b408c8dc8faf76f77/src/net/KNet/Specific/Serialization/KNetSerialization.cs#L275 does not work right in this way, you must use something like: `JVMBridgeBase.Wraps<Java.Lang.Double>(_DoubleDeserializer.Deserialize(topic, data) as IJavaObject);` 

_Originally posted by @mariomastrodicasa in https://github.com/masesgroup/KNet/pull/222#discussion_r1347351064_

### PR DESCRIPTION
**Pull request by masesdevelopers**
## Description

Update cast to Java type with `JVMBridgeBase.Wraps`

## Related Issue

Closed #245 

## How Has This Been Tested?

Local test on returned object from JVM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by mariomastrodicasa — APPROVED** [review]

File: src/net/KNet/Specific/Serialization/KNetSerialization.cs [hunk 1]
```diff
@@ -290,7 +290,7 @@ public static float DeserializeFloat(string topic, byte[] data)
         /// </summary>
         public static int DeserializeInt(string topic, byte[] data)
         {
-            return (int)_IntDeserializer.Deserialize(topic, data);
+            return JVMBridgeBase.Wraps<Java.Lang.Integer>(_IntDeserializer.Deserialize(topic, data) as IJavaObject);
```
Comment (mariomastrodicasa) [inline src/net/KNet/Specific/Serialization/KNetSerialization.cs:293]: Running the tests related to `KNetCompactedReplicator` seems the result of `Deserialize` is not always a Java object. I don't understand why but the result is an `int` instead of `java.lang.Integer` even if the Java signature is `public Integer deserialize(String topic, byte[] data)`. Maybe a better implementation needs a check against `IJavaObject`.
