### PR TITLE
Fix serialization/deserialization of types managed form Apache Kafka

### LINKED ISSUE #221: KNetSerDes does not work when types managed from Apache Kafka are used as key or value
**Describe the bug**
The class https://github.com/masesgroup/KNet/blob/48420b5524ef930bb68152c795ae7498c25550e1/src/net/KNet/Specific/Serialization/KNetSerDes.cs#L30 does not work well using types managed from Apache Kafka.

**To Reproduce**
1. Try to allocate [KNetProducer ](https://github.com/masesgroup/KNet/blob/48420b5524ef930bb68152c795ae7498c25550e1/src/net/KNet/Specific/Producer/KNetProducer.cs#L278) using an `int` as key
2. Try to produce something
3. An exception is raised

**Expected behavior**
The record is produced to the topic

**Screenshots**
No screenshot

**Additional context**
The problem seems related to the SerSes allocated from [KNetSerialization](https://github.com/masesgroup/KNet/blob/master/src/net/KNet/Specific/Serialization/KNetSerialization.cs
)

### PR DESCRIPTION
**Pull request by masesdevelopers**
## Description

The PR solves an issue with types managed from Apache Kafka during serialization/deserialization

## Related Issue

Closed #221 

## How Has This Been Tested?

Locally tested

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: src/net/KNet/Specific/Serialization/KNetSerialization.cs [hunk 1]
```diff
@@ -247,49 +248,49 @@ public static byte[] DeserializeByteArray(string topic, byte[] data)
...
 
-        static readonly Deserializer<double> _DoubleDeserializer = new DoubleDeserializer();
+        static readonly DoubleDeserializer _DoubleDeserializer = new DoubleDeserializer();
         /// <summary>
         /// Deserialize a <see cref="SerializationType.Double"/>
         /// </summary>
         public static double DeserializeDouble(string topic, byte[] data)
         {
-            return _DoubleDeserializer.Deserialize(topic, data);
+            return (double)_DoubleDeserializer.Deserialize(topic, data);
```
Comment (mariomastrodicasa) [inline src/net/KNet/Specific/Serialization/KNetSerialization.cs:275]: The cast does not work right in this way, you must use something like: JVMBridgeBase.Wraps<Java.Lang.Double>(_DoubleDeserializer.Deserialize(topic, data) as IJavaObject);
